version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: wordle
      POSTGRES_USER: wordle
      POSTGRES_PASSWORD: wordle
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/wordle
      SPRING_DATASOURCE_USERNAME: wordle
      SPRING_DATASOURCE_PASSWORD: wordle
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:          # ↙︎ 코드-실행 동기화를 원하면 추가 (선택)
      - ./:/workspace  # 컨테이너 /workspace ↔ 로컬 리포 동기화
