spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health, info
app:
  opendict:
    search:
      base-url: https://opendict.korean.go.kr/api/search
      certkey-no: 7818
      key: ${OPEN_DICT_KEY}       # ← 환경변수에서 주입
      target-type: search
      req-type: json              # JSON 권장
      part: word
      sort: dict
      start: 1
      num: 10
      advanced: y
      method: exact               # exact|start|include (원하면 변경)

    view:
      base-url: https://opendict.korean.go.kr/api/view
      target-type: view
      req-type: json
      method: word_info