spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  redis:
    host: ${SPRING_REDIS_HOST}
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health, info
