spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate  # OAuth2 테이블은 Flyway로 관리
    open-in-view: false
    properties:
      hibernate:
        # OAuth2 테이블은 JPA 관리 대상에서 제외
        hbm2ddl:
          auto: validate
  
  # 캐시 설정 (Caffeine으로 변경)
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=10m

  # 프로파일별 설정
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

management:
  endpoints:
    web:
      exposure:
        include: health, info

# 로깅 설정
logging:
  level:
    com.example.wordle.security: DEBUG
    org.springframework.security: INFO
